# Generated by Django 5.0 on 2023-12-14 14:04

from django.db import migrations
from django.apps import apps as global_apps


def forwards(apps, schema_editor):
    try:
        OldModel = apps.get_model("oc_lettings_site", "Profile")
    except LookupError:
        # The old app isn't installed.
        return

    NewModel = apps.get_model("profiles", "Profile")
    NewModel.objects.bulk_create(
        NewModel(user=old_object.user,
                 favorite_city=old_object.favorite_city,
                 )
        for old_object in OldModel.objects.all()
    )
    


class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    if global_apps.is_installed("oc_lettings_site"):
        dependencies.append(("oc_lettings_site", "0001_initial"))



