# Generated by Django 5.0 on 2023-12-14 12:16

from django.db import migrations
from django.apps import apps as global_apps


def forwards(apps, schema_editor):
    try:
        OldModel = apps.get_model("oc_lettings_site", "Letting")
    except LookupError:
        # The old app isn't installed.
        return

    NewModel = apps.get_model("lettings", "Letting")
    NewModel.objects.bulk_create(
        NewModel(
            title=old_object.title,
            address_id=old_object.address_id,
        )
        for old_object in OldModel.objects.all()
    )


class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
    dependencies = [
        ("lettings", "0002_auto_20231214_1249"),
    ]

    if global_apps.is_installed("oc_lettings_site"):
        dependencies.append(("oc_lettings_site", "0001_initial"))


