# Generated by Django 5.0 on 2023-12-23 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lettings", "0003_auto_20231214_1316"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Adress", "verbose_name_plural": "Adresses"},
        ),
    ]
